### ISSUE TITLE
Need a mechanism for disabling plugins in the event that an error occurs internally in the plugin

### ISSUE THREAD

**Issue by Spaz-Master** [FoxGenesis/Watamebot#17]
Currently if something goes wrong in a plugin (a needed file is not present, or an external executable is not installed that is called by the plugin, etc) then an exception will be raised every time that error occurs instead of terminating that plugin.

**Comment by AshlyneS** [comment]
added in a20902145d730f53e57fcc9c5780b3db206d100b
